#
# Makefile for subordinate directory
#
#	This directory and its include above are an inherited kludge,
#	and someday will be fixed or lost.
#

all clean install:
	cd src ; make $(MFLAGS) $@ DESTDIR=$(DESTDIR)
