#! /bin/sh
#
# @(#)fix_domainname 1.1 86/09/25 SMI; from UCB X.X XX/XX/XX
#
if [ $# -ne 2 ]
then
	echo "Usage: $0 dir domainname"
	exit 1
fi
cd $1
ed - rc.local <<END
/domainname/s/ [^ ]*\$/ $2/
w
q
END
