#
# @(#)Makefile 1.3 87/01/07 SMI;
#

OBJSLIB=\
	ndet_auto.o	ndet_g_itimer.o	ndet_p_event.o	ndet_s_out.o \
	ndet_event.o	ndet_g_out.o	ndet_read.o	ndet_s_pri.o \
	ndet_fcntl.o	ndet_g_pri.o	ndet_remove.o	ndet_s_sig.o \
	ndet_fd.o	ndet_g_sig.o	ndet_s_death.o ndet_s_wait.o \
	ndet_g_death.o	ndet_g_wait.o	ndet_s_event.o	ndet_select.o \
	ndet_g_event.o	ndet_get_func.o	ndet_s_except.o	ndet_sig.o \
	ndet_g_except.o	ndet_itimer.o	ndet_s_fd.o	ndet_value.o \
	ndet_g_fd.o	ndet_loop.o	ndet_s_in.o	ndet_wait.o \
	ndet_g_in.o	ndet_p_death.o	ndet_s_itimer.o ndet_death.o \
	ndet_die.o	ndet_veto.o	ndet_do_dis.o	ndet_no_dis.o \
	ndet_single.o \
	\
	ndis_d_pri.o	ndis_d_sched.o	ndis_dispatch.o	ndis_g_sched.o \
	ndis_s_sched.o	ndis_d_wait.o \
	\
	ntfy_client.o	ntfy_cond.o	ntfy_debug.o	ntfy_list.o \
	ntfy_node.o	ntfy_protect.o	ntfy_perror.o	ntfy_dump.o \
	\
	sys_select.o	sys_read.o	sys_fcntl.o \
	\
	nint_copy.o	nint_i_sig.o	nint_n_out.o	nint_r_itimer.o \
	nint_get.o	nint_i_wait.o	nint_n_sig.o	nint_r_out.o \
	nint_i_death.o	nint_inter.o	nint_n_wait.o	nint_r_sig.o \
	nint_i_event.o	nint_n_death.o	nint_next.o	nint_r_wait.o \
	nint_i_except.o	nint_n_event.o	nint_r_death.o	nint_remove.o \
	nint_i_fd.o	nint_n_except.o	nint_r_event.o	nint_set.o \
	nint_i_in.o	nint_n_fd.o	nint_r_except.o	nint_stack.o \
	nint_i_itimer.o	nint_n_in.o	nint_r_fd.o \
	nint_i_out.o	nint_n_itimer.o	nint_r_in.o

CFILESLIB=\
	ndet_auto.c	ndet_g_itimer.c	ndet_p_event.c	ndet_s_out.c \
	ndet_event.c	ndet_g_out.c	ndet_read.c	ndet_s_pri.c \
	ndet_fcntl.c	ndet_g_pri.c	ndet_remove.c	ndet_s_sig.c \
	ndet_fd.c	ndet_g_sig.c	ndet_s_death.c	ndet_s_wait.c \
	ndet_g_death.c	ndet_g_wait.c	ndet_s_event.c	ndet_select.c \
	ndet_g_event.c	ndet_get_func.c	ndet_s_except.c	ndet_sig.c \
	ndet_g_except.c	ndet_itimer.c	ndet_s_fd.c	ndet_value.c \
	ndet_g_fd.c	ndet_loop.c	ndet_s_in.c	ndet_wait.c \
	ndet_g_in.c	ndet_p_death.c	ndet_s_itimer.c ndet_death.c \
	ndet_die.c	ndet_veto.c	ndet_do_dis.c	ndet_no_dis.c \
	ndet_single.c \
	\
	ndis_d_pri.c	ndis_d_sched.c	ndis_dispatch.c	ndis_g_sched.c \
	ndis_s_sched.c	ndis_d_wait.c \
	\
	ntfy_client.c	ntfy_cond.c	ntfy_debug.c	ntfy_list.c \
	ntfy_node.c	ntfy_protect.c	ntfy_perror.c	ntfy_dump.c \
	\
	sys_select.c	sys_read.c	sys_fcntl.c \
	\
	nint_copy.c	nint_i_sig.c	nint_n_out.c	nint_r_itimer.c \
	nint_get.c	nint_i_wait.c	nint_n_sig.c	nint_r_out.c \
	nint_i_death.c	nint_inter.c	nint_n_wait.c	nint_r_sig.c \
	nint_i_event.c	nint_n_death.c	nint_next.c	nint_r_wait.c \
	nint_i_except.c	nint_n_event.c	nint_r_death.c	nint_remove.c \
	nint_i_fd.c	nint_n_except.c	nint_r_event.c	nint_set.c \
	nint_i_in.c	nint_n_fd.c	nint_r_except.c	nint_stack.c \
	nint_i_itimer.c	nint_n_in.c	nint_r_fd.c \
	nint_i_out.c	nint_n_itimer.c	nint_r_in.c

GPROFFILESALL=\
	ndet_auto.pg	ndet_g_itimer.pg	ndet_p_event.pg	ndet_s_out.pg \
	ndet_event.pg	ndet_g_out.pg	ndet_read.pg	ndet_s_pri.pg \
	ndet_fcntl.pg	ndet_g_pri.pg	ndet_remove.pg	ndet_s_sig.pg \
	ndet_fd.pg	ndet_g_sig.pg	ndet_s_death.pg ndet_s_wait.pg \
	ndet_g_death.pg	ndet_g_wait.pg	ndet_s_event.pg	ndet_select.pg \
	ndet_g_event.pg	ndet_get_func.pg	ndet_s_except.pg	ndet_sig.pg \
	ndet_g_except.pg	ndet_itimer.pg	ndet_s_fd.pg	ndet_value.pg \
	ndet_g_fd.pg	ndet_loop.pg	ndet_s_in.pg	ndet_wait.pg \
	ndet_g_in.pg	ndet_p_death.pg	ndet_s_itimer.pg ndet_death.pg \
	ndet_die.pg	ndet_veto.pg	ndet_do_dis.pg	ndet_no_dis.pg \
	ndet_single.pg \
	\
	ndis_d_pri.pg	ndis_d_sched.pg	ndis_dispatch.pg	ndis_g_sched.pg \
	ndis_s_sched.pg	ndis_d_wait.pg \
	\
	ntfy_client.pg	ntfy_cond.pg	ntfy_debug.pg	ntfy_list.pg \
	ntfy_node.pg	ntfy_protect.pg	ntfy_perror.pg	ntfy_dump.pg \
	\
	sys_select.pg	sys_read.pg	sys_fcntl.pg \
	\
	nint_copy.pg	nint_i_sig.pg	nint_n_out.pg	nint_r_itimer.pg \
	nint_get.pg	nint_i_wait.pg	nint_n_sig.pg	nint_r_out.pg \
	nint_i_death.pg	nint_inter.pg	nint_n_wait.pg	nint_r_sig.pg \
	nint_i_event.pg	nint_n_death.pg	nint_next.pg	nint_r_wait.pg \
	nint_i_except.pg	nint_n_event.pg	nint_r_death.pg	nint_remove.pg \
	nint_i_fd.pg	nint_n_except.pg	nint_r_event.pg	nint_set.pg \
	nint_i_in.pg	nint_n_fd.pg	nint_r_except.pg	nint_stack.pg \
	nint_i_itimer.pg	nint_n_in.pg	nint_r_fd.pg \
	nint_i_out.pg	nint_n_itimer.pg	nint_r_in.pg
HDRSLIB=notify.h ntfy.h ndis.h ndet.h
GPROFLIBFILE= libnotify_p.a

CFILESALL=$(CFILESLIB)
HDRSALL=$(HDRSLIB)
SRCSALL=$(CFILESALL) $(HDRSALL) Makefile

AWK=	/bin/awk
TOUCH=	touch -c
CTAGS=	/usr/ucb/ctags -w
DESTDIR=
CPUFLAG=
PROFILE=

INCLUDE=/usr/include

DBX=
CFLAGS=	-O -I$(INCLUDE)
CFLAGS_LOCAL=

CFLAGS_NOT_ROI_DATA= $(CFLAGS) $(DBX) $(CFLAGS_LOCAL) $(CPUFLAG)
.SUFFIXES: .pg

LDFLAGS=
LINTFLAGS=	-I.

.c.o:
	cc $(CFLAGS_NOT_ROI_DATA) -A-R -c $<

.c.pg:
	if [ -f $*.o ]; then \
		mv $*.o $*.o.tmp; \
	fi
	${CC} ${CFLAGS_NOT_ROI_DATA} -pg -c $<
	-mv $*.o $*.pg
	if [ -f $*.o.tmp ]; then \
		mv $*.o.tmp $*.o; \
	fi


all: libnotify.a

libnotify.a:	$(OBJSLIB)
	ar uv libnotify.a $?
	ranlib libnotify.a

gprof::  ${GPROFLIBFILE}

${GPROFLIBFILE}:: ${GPROFFILESALL}
	ar uvl ${GPROFLIBFILE} $?
	ranlib ${GPROFLIBFILE}

install: install_h

#	FIXED so don't have to do a CFLAGS_NOT_ROI_DATA: ndet_loop.c,
#	ntfy_debug.c

#	Can change ndis_default_scheduler in ndis_dispatch.c
ndis_dispatch.o:
	cc ${CFLAGS_NOT_ROI_DATA} -c ndis_dispatch.c
 
install_h:
	-for i in notify.h; do \
		cmp -s $$i ${DESTDIR}/usr/include/sunwindow/$$i || \
		install -c -m 644 $$i ${DESTDIR}/usr/include/sunwindow/$$i; \
	done

install_lib: libnotify.a
	install -c -m 644 libnotify.a ${DESTDIR}/usr/lib
	ranlib ${DESTDIR}/usr/lib/libnotify.a

devinstall: libnotify.a
	install -c -m 644 libnotify.a /usr/lib
	ranlib /usr/lib/libnotify.a

tar:
	echo You will want to have an empty directory that you are taring to!
	tar fc - . | rsh ${DESTMACH} \
		"cd /usr/src/sun/usr.lib/libnotify;tar xpBf -;"

clean:
	rm -f *.o libnotify.a core *.pg

$(SRCSALL):
	sccs get $@;

srcsget: $(SRCSALL)

tags:	$(CFILESALL)
	${CTAGS} $(CFILESALL);

print:	$(SRCSALL)
	pr -f $(SRCSALL) | rsh krypton lpr -Pimagen -r

lint:
	lint $(LINTFLAGS) $(CFILESALL)

FRC:
# non-existent so always younger

depend:
	make_depend -I${INCLUDE} ${CFILESALL}

#include Make.depend

# DO NOT DELETE THIS LINE -- make depend uses it
ndet_auto.o: ndet_auto.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h

ndet_g_itimer.o: ndet_g_itimer.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_p_event.o: ndet_p_event.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h \
	nint.h

ndet_s_out.o: ndet_s_out.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_event.o: ndet_event.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_g_out.o: ndet_g_out.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_read.o: ndet_read.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h

ndet_s_pri.o: ndet_s_pri.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h

ndet_fcntl.o: ndet_fcntl.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_g_pri.o: ndet_g_pri.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_remove.o: ndet_remove.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h

ndet_s_sig.o: ndet_s_sig.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

ndet_fd.o: ndet_fd.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_g_sig.o: ndet_g_sig.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_s_death.o: ndet_s_death.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

ndet_s_wait.o: ndet_s_wait.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

ndet_g_death.o: ndet_g_death.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_g_wait.o: ndet_g_wait.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_s_event.o: ndet_s_event.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

ndet_select.o: ndet_select.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h

ndet_g_event.o: ndet_g_event.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_get_func.o: ndet_get_func.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

ndet_s_except.o: ndet_s_except.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_sig.o: ndet_sig.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_g_except.o: ndet_g_except.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_itimer.o: ndet_itimer.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h \
	nint.h

ndet_s_fd.o: ndet_s_fd.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

ndet_value.o: ndet_value.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_g_fd.o: ndet_g_fd.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_loop.o: ndet_loop.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h \
	ndis.h

ndet_s_in.o: ndet_s_in.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_wait.o: ndet_wait.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_g_in.o: ndet_g_in.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_p_death.o: ndet_p_death.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h

ndet_s_itimer.o: ndet_s_itimer.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

ndet_death.o: ndet_death.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h \
	nint.h

ndet_die.o: ndet_die.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h

ndet_veto.o: ndet_veto.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_do_dis.o: ndet_do_dis.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_no_dis.o: ndet_no_dis.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ndet_single.o: ndet_single.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h

ndis_d_pri.o: ndis_d_pri.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndis.h

ndis_d_sched.o: ndis_d_sched.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndis.h

ndis_dispatch.o: ndis_dispatch.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndis.h \
	nint.h \
	ndet.h

ndis_g_sched.o: ndis_g_sched.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndis.h

ndis_s_sched.o: ndis_s_sched.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndis.h

ndis_d_wait.o: ndis_d_wait.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndis.h

ntfy_client.o: ntfy_client.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndis.h

ntfy_cond.o: ntfy_cond.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h

ntfy_debug.o: ntfy_debug.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h

ntfy_list.o: ntfy_list.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h

ntfy_node.o: ntfy_node.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h

ntfy_protect.o: ntfy_protect.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h

ntfy_perror.o: ntfy_perror.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h

ntfy_dump.o: ntfy_dump.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	ndis.h

sys_select.o: sys_select.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h

sys_read.o: sys_read.c

sys_fcntl.o: sys_fcntl.c

nint_copy.o: nint_copy.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_i_sig.o: nint_i_sig.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_n_out.o: nint_n_out.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_r_itimer.o: nint_r_itimer.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_get.o: nint_get.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_i_wait.o: nint_i_wait.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_n_sig.o: nint_n_sig.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_r_out.o: nint_r_out.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	nint.h

nint_i_death.o: nint_i_death.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_inter.o: nint_inter.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_n_wait.o: nint_n_wait.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_r_sig.o: nint_r_sig.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_i_event.o: nint_i_event.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_n_death.o: nint_n_death.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_next.o: nint_next.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_r_wait.o: nint_r_wait.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_i_except.o: nint_i_except.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	nint.h

nint_n_event.o: nint_n_event.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_r_death.o: nint_r_death.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_remove.o: nint_remove.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_i_fd.o: nint_i_fd.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_n_except.o: nint_n_except.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_r_event.o: nint_r_event.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_set.o: nint_set.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_i_in.o: nint_i_in.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	nint.h

nint_n_fd.o: nint_n_fd.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_r_except.o: nint_r_except.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	nint.h

nint_stack.o: nint_stack.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_i_itimer.o: nint_i_itimer.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_n_in.o: nint_n_in.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_r_fd.o: nint_r_fd.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_i_out.o: nint_i_out.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	nint.h

nint_n_itimer.o: nint_n_itimer.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	ndet.h \
	nint.h

nint_r_in.o: nint_r_in.c \
	ntfy.h \
	${INCLUDE}/sunwindow/notify.h \
	nint.h



# DEPENDENCIES MUST END AT END OF FILE
# IF YOU PUT STUFF HERE IT WILL GO AWAY
# SEE HOW make depend WORKS FOR FURTHER INFO
